### ISSUE TITLE
Versão 8 realmente implementada?

### ISSUE THREAD

**Issue by daniloceano** [pedrospeixoto/MPAS-BR#6]
Olá!

Temos certeza de que a versão 8 foi realmente implementada? Compilei o repositório novamente por aqui e quando fui tentar fazer o processamento dos dados estáticos eu obtive:

> 
> ----------------------------------------------------------------------
> Beginning MPAS-init_atmosphere Error Log File for task      39 of      50
>     Opened at 2023/07/26 18:39:10
> ----------------------------------------------------------------------
> 
> ERROR: ****************************************************************
> ERROR: Error: Interpolation of static fields does not work in parallel.
> ERROR: Please run the static_interp step using only a single MPI task.
> CRITICAL ERROR: ****************************************************************
> Logging complete.  Closing file at 2023/07/26 18:39:10
> 

No caso, a partir da versão 8, deveria ser possível realizar isso. Só para que eu saiba a partir de onde atacar o erro

**Comment by favba** [comment]
Oi Danilo.
Você fez o checkout do branch `MPAS-Dev_master` antes de tentar rodar correto?
Este branch é uma cópia exata do V8.0.1 do MPAS, se nenhuma modificação nossa. Então deveria funcionar da mesma maneira que o código original.
O processamento desta parte em paralelo é uma das novidades da v8, certo?

Uma coisa que eu já reparei com o MPAS é que o quando você tem já partes do código compilados, e faz algumas mudanças, e depois faz um `make gfortran CORE=....`, ele às vezes não captura as mudanças bem. Estou imaginando que você tinha o branch `master` "checked-out" e compilado. Depois fez o checkout do branch da V8.0.1 e compilou novamente. Mas desconfio que parte dos módulos ou objetos ainda estão na versão 7.

Tenta fazer o seguinte, clona em um outra pasta novamente o repositório, faz o checkout do branch `MPAS-Dev_master` e compila e roda assim, sem ter compilado nenhum outro branch antes dele. Vê se assim não funciona.
